spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PohKaiBoon/cloudConfigServer
          clone-on-start: true
server:
  port: 9196
