server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: incident-service
          uri: lb://incident-service
          predicates:
            - Path=/incident/**
          filters:
            - AuthenticationFilter
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9196

