server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/incidents_db
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: incident-service
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9196
  rabbitmq:
    addresses: localhost:5672

