server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://${$DB_HOST:localhost}:3307/incidents_db
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: incident-service
  config:
    import: configserver:http://localhost:9196

