server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/jwt_security
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: authentication-service
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9196
